POST http://localhost:5000/season?name=2017/2018
Accept: */*
Cache-Control: no-cache
clientID: 44d50934-ed6c-45bb-abfc-dcb3e242c9a5
apiKey: 5b55aa8a1da5513373710bc844f0b227b0cd96c2
Content-Type: application/x-www-form-urlencoded
x-access-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjbGllbnRJZCI6IjNiYmViZGY5LTZkOTgtNDA1Ny1hNzlmLTdjYjhjMWE3MTk2NiIsImVtYWlsIjoiY2FybG9zQGdtYWlsLnB0IiwidHlwZSI6InBhcmVudCIsImV4cCI6MTU1MDUzMzM3NX0.9BGbX75bFtbu3FVkp1YirsEGgwY9cJpMdEaYfqKSuBc

###

